package mocks

import auth "github.com/control-center/serviced/auth"
import mock "github.com/stretchr/testify/mock"

// HostExpirationRegistryInterface is an autogenerated mock type for the HostExpirationRegistryInterface type
type HostExpirationRegistryInterface struct {
	mock.Mock
}

// IsExpired provides a mock function with given fields: _a0
func (_m *HostExpirationRegistryInterface) IsExpired(_a0 string) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: _a0
func (_m *HostExpirationRegistryInterface) Remove(_a0 string) {
	_m.Called(_a0)
}

// Set provides a mock function with given fields: _a0, _a1
func (_m *HostExpirationRegistryInterface) Set(_a0 string, _a1 int64) {
	_m.Called(_a0, _a1)
}

var _ auth.HostExpirationRegistryInterface = (*HostExpirationRegistryInterface)(nil)
