package mocks

import "github.com/stretchr/testify/mock"

import "crypto"

// KeyStore is an autogenerated mock type for the KeyStore type
type KeyStore struct {
	mock.Mock
}

// MasterPublicKey provides a mock function with given fields:
func (_m *KeyStore) MasterPublicKey() crypto.PublicKey {
	ret := _m.Called()

	var r0 crypto.PublicKey
	if rf, ok := ret.Get(0).(func() crypto.PublicKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PublicKey)
		}
	}

	return r0
}

// PrivateKey provides a mock function with given fields:
func (_m *KeyStore) PrivateKey() crypto.PrivateKey {
	ret := _m.Called()

	var r0 crypto.PrivateKey
	if rf, ok := ret.Get(0).(func() crypto.PrivateKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PrivateKey)
		}
	}

	return r0
}

// PublicKey provides a mock function with given fields:
func (_m *KeyStore) PublicKey() crypto.PublicKey {
	ret := _m.Called()

	var r0 crypto.PublicKey
	if rf, ok := ret.Get(0).(func() crypto.PublicKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PublicKey)
		}
	}

	return r0
}
