package mocks

import auth "github.com/control-center/serviced/auth"
import mock "github.com/stretchr/testify/mock"

// RPCHeaderBuilder is an autogenerated mock type for the RPCHeaderBuilder type
type RPCHeaderBuilder struct {
	mock.Mock
}

// BuildHeader provides a mock function with given fields: _a0
func (_m *RPCHeaderBuilder) BuildHeader(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ auth.RPCHeaderBuilder = (*RPCHeaderBuilder)(nil)
