package mocks

import auth "github.com/control-center/serviced/auth"
import mock "github.com/stretchr/testify/mock"

// RPCHeaderParser is an autogenerated mock type for the RPCHeaderParser type
type RPCHeaderParser struct {
	mock.Mock
}

// ParseHeader provides a mock function with given fields: header, request
func (_m *RPCHeaderParser) ParseHeader(header []byte, request []byte) (auth.Identity, error) {
	ret := _m.Called(header, request)

	var r0 auth.Identity
	if rf, ok := ret.Get(0).(func([]byte, []byte) auth.Identity); ok {
		r0 = rf(header, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Identity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(header, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ auth.RPCHeaderParser = (*RPCHeaderParser)(nil)
