package mocks

import "github.com/stretchr/testify/mock"

import . "gopkg.in/check.v1"

// Verifier is an autogenerated mock type for the Verifier type
type Verifier struct {
	mock.Mock
}

// Verify provides a mock function with given fields: message, signature
func (_m *Verifier) Verify(message []byte, signature []byte) error {
	ret := _m.Called(message, signature)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = rf(message, signature)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
