package mocks

import iostat "github.com/control-center/serviced/utils/iostat"
import mock "github.com/stretchr/testify/mock"
import time "time"

// Getter is an autogenerated mock type for the Getter type
type Getter struct {
	mock.Mock
}

// GetIOStatsCh provides a mock function with given fields:
func (_m *Getter) GetIOStatsCh() (<-chan map[string]iostat.DeviceUtilizationReport, error) {
	ret := _m.Called()

	var r0 <-chan map[string]iostat.DeviceUtilizationReport
	if rf, ok := ret.Get(0).(func() <-chan map[string]iostat.DeviceUtilizationReport); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan map[string]iostat.DeviceUtilizationReport)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStatInterval provides a mock function with given fields:
func (_m *Getter) GetStatInterval() time.Duration {
	ret := _m.Called()

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

var _ iostat.Getter = (*Getter)(nil)
