#!/usr/bin/env bash


if [[ -z "$GOPATH" ]]; then
	echo "GOPATH is not set"
	exit 1
fi

if [[ -z "$1" ]]; then
	echo "cpToBin requires an arg"
fi

GP="$( cut -d ':' -f 1 <<< "$GOPATH" )"
cp -pv $1 $GP/bin

