#! /usr/bin/env bash

# Copyright 2015 The Serviced Authors.                                                                                                     
# Licensed under the Apache License, Version 2.0 (the "License");               
# you may not use this file except in compliance with the License.              
# You may obtain a copy of the License at                                       
#                                                                               
#     http://www.apache.org/licenses/LICENSE-2.0                                                                                               
#                                                                               
# Unless required by applicable law or agreed to in writing, software           
# distributed under the License is distributed on an "AS IS" BASIS,             
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.        
# See the License for the specific language governing permissions and           
# limitations under the License. 

BTRFS_BALANCE_default="/opt/serviced/var /opt/serviced/var/volumes /var/lib/docker"
: ${BTRFS_BALANCE=${BTRFS_BALANCE_default}}

for DISK in $BTRFS_BALANCE; do
    if [[ `df --output=fstype $DISK | tail -1 | grep btrfs` ]]; then
        btrfs balance start $DISK
    else
        echo $DISK is not btrfs
    fi
done
