#!/bin/sh

if [ ! -d /opt/serviced/log/zenossdbpack ]; then
    mkdir -p /opt/serviced/log/zenossdbpack
    chmod 1777 /opt/serviced/log/zenossdbpack
fi

# no reason to run zenossdbpack on agents.
if 
	grep --quiet ^SERVICED_MASTER=1 /etc/default/serviced 
then
	${SERVICED:=/opt/serviced/bin/serviced} service run --mount /opt/serviced/log/zenossdbpack,/opt/zenoss/log zope zenossdbpack
fi
