FROM ubuntu:trusty
MAINTAINER Zenoss <dev@zenoss.com>

RUN groupadd -f -g %GID% zenoss
RUN useradd -d /home/zenoss -m -s /bin/bash -u %UID% -g %GID% zenoss 
RUN echo "zenoss ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN apt-get -y install npm
RUN npm install -g grunt-cli
RUN npm install grunt-contrib-uglify
RUN npm install grunt-contrib-concat
RUN ln -s /usr/bin/nodejs /usr/bin/node

USER zenoss
CMD ["grunt"]
